App/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.Index.as_view(), name = 'inicio'),

]

report/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

App/models.py
from django.db import models
from django import forms

class Customer(models.Model):
    id = models.AutoField(primary_key = True)
    name = models.CharField(max_length = 30)
    parser_choise = (
        ('A', 'parser 1'),
        ('B', 'parser 2'),
        ('C', 'parcer 3'),
        ('C', 'parcer 4'),
    )
    parser = models.CharField(max_length = 1, choices=parser_choise)

    def __str__(self):
        return self.name




class FileParser(models.Model):
    id = models.AutoField(primary_key = True)
    customer = models.ForeignKey(Customer , on_delete=models.CASCADE)
    email_id = models.IntegerField(default=0)
    email_date  =  models.DateTimeField()
    #list_parser
    option_uploand = (
                     ('byEmail' , 'Email'),
                     ('uploand_by_web' , 'Web'),
                     )

    send = (
        ('True' , 'true'),
        ('False' , 'false'),
    )
    option = models.CharField(max_length = 30 , choices = option_uploand)
    sended  = models.CharField(max_length = 30 , choices = send)
    file_name = models.FileField(upload_to= 'uploads/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
       return self.customer.name

    def get_info(self):
        return 'id {} , customer {} , email_id {} , email_date {} ,  option {}, sended {}'.format(self.id , self.customer ,self.email_id , self.email_date , self.option ,self.sended )

App/views.py
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView , DetailView
from App.models import Customer , FileParser
from App.form import CustomerForm , FileParserForm , FilterForm
from django.views import View
from django.shortcuts import render
from django.urls import reverse_lazy
from .export_process import *
from .tasks import export_file , sendmail
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "App/index.html"

class CreateCustom(CreateView):
    model = Customer
    form_class = CustomerForm
    template_name = 'App/'
    success_url = reverse_lazy('homeview')


class CreateFileParser(CreateView):
    model = FileParser
    form_class = FileParserForm
    template_name = 'App/'
    success_url = reverse_lazy('create_file')


class FilterView(View):

    def __init__(self):
        self.template_name = 'App/filter.html'
        self.customers = Customer.objects.all()


    def get(self ,request):
        return render(request, self.template_name ,{'customers':self.customers})

    def post(self ,request):
        info_request= {'filter_by':request.POST['filter_by'] , 'customer_id':request.POST['customer'],
                       'initial_date':request.POST['initial_date'] ,'final_date': request.POST['final_date'],
                       'status':request.POST['status']}

        task1 = export_file.delay(info_request)
        task2 = sendmail.delay()
        return HttpResponse(task1)

class Index(View):

    def __init__(self):
        self.template_name = 'App/index.html'
        self.customers = Customer.objects.all()


    def get(self ,request):
        return render(request, self.template_name ,{'customers':self.customers})

    def post(self ,request):
        print(request.POST)
        info_request= {'filter_by':request.POST['filter_by'] , 'customer_id':request.POST['customer'],
                       'initial_date':request.POST['initial_date'] ,'final_date': request.POST['final_date'],
                       'status':request.POST['status']}

        task1 = export_file.delay(info_request)
        task2 = sendmail.delay()
        return HttpResponse(task1)

templates/App/filter.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'reporteApp/style.css' %}">


<div class="container">
  <form id="contact" method="post">
    {% csrf_token %}
    <h3>Filter Info</h3>
    <h4>Contact us for custom quote</h4>
    <fieldset>
      <label>Customer</label>
      <select name = 'customer' >
        {% if customers %}
          {% for customer in customers %}
        <option value={{customer.id}}>{{customer.name}}</option>
        {% endfor %}
        {% endif %}
      </select>
    </fieldset>
    <fieldset>
      <label>Filter by</label>
      <select name = 'filter_by'>
        <option value='email'>Email</option>
        <option value='date'>Date</option>
      </select>

    </fieldset>

    <fieldset>
      <label>Date Initial </label>
      <input type = 'date' name = 'initial_date'>
      <label>Finishied Date </label>
      <input type = 'date' name = 'final_date'>
    </fieldset>

    <fieldset>
      <label>Status Send </label>
       <select name ='status'>
        <option value='True'>True</option>
        <option value='False'>False</option>
      </select>
      <button class="btn btn-primary">Send</button>
    </fieldset>

  </form>
</div>
</body>

templates/App/index.html
<!DOCTYPE html>
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<style>
    body, h1, h5 {
        font-family: "Raleway", sans-serif
    }

    body, html {
        height: 100%
    }

    .bgimg {
        background-image: url('https://3er1viui9wo30pkxh1v2nh4w-wpengine.netdna-ssl.com/wp-content/uploads/prod/sites/68/2018/11/icons_blk_flatangle_00005.png');

        min-height: 100%;
        background-position: center;
        background-size: cover;
    }
</style>
<body>

<div class="bgimg w3-display-container w3-text-white">
    <div class="w3-display-middle w3-jumbo">
        <p>logo</p>
    </div>
    <div class="w3-display-topleft w3-container w3-xlarge">
        <p>
            <button onclick="document.getElementById('customer').style.display='block'" class="w3-button w3-black">
                Create Customer
            </button>
        </p>
        <p>
            <button onclick="document.getElementById('file').style.display='block'" class="w3-button w3-black">
                Add File
            </button>
        </p>
        <p>
            <button onclick="document.getElementById('Filter').style.display='block'" class="w3-button w3-black">
                Filter
            </button>
        </p>
    </div>
    <div class="w3-display-bottomleft w3-container">

        <p>By.<a href="https://www.instagram.com/morenovelasqz/" target="_blank">Velasqz</a></p>
    </div>
</div>


<!-- Create Customer -->

<div class="container">
    <form id="contact" method="post">
        {% csrf_token %}
        <div id="customer" class="w3-modal">
            <div class="w3-modal-content w3-animate-zoom">
                <div class="w3-container w3-black">
            <span onclick="document.getElementById('customer').style.display='none'"
                  class="w3-button w3-display-topright w3-large">x</span>
                    <h1>Customer</h1>
                </div>
                <div class="w3-container">
                    <form id="customer" method="post">
                        <fieldset>
                            <label>Name:</label>
                            <input class=type="text" placeholder="Name" required name="Name">

                        </fieldset>
                        <fieldset>
                            <label>Parser:</label>
                            <select name='filter_by'>
                                <option value=>...</option>
                                <option value='date'>Parser 1</option>
                                <option value='date'>Parcer 2</option>
                                <option value='date'>Parcer 3</option>
                                <option value='date'>Parcer 4</option>
                            </select>
                        </fieldset>
                        <button class="btn btn-primary" style="float: right">Send</button>
                    </form>
                </div>
            </div>
        </div>


        <!-- Add File -->


        <div id="file" class="w3-modal">
            <div class="w3-modal-content w3-animate-zoom">
                <div class="w3-container w3-black w3-display-container">
            <span onclick="document.getElementById('file').style.display='none'"
                  class="w3-button w3-display-topright w3-large">x</span>
                    <h1>Add File</h1>
                </div>
                <div class="w3-container">
                    <form id="file" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <label>Customer</label>
                            <select name='customer'>
                                {% if customers %}
                                    {% for customer in customers %}
                                        <option value={{ customer.id }}>{{ customer.name }}</option>
                                    {% endfor %}
                                {% endif %}
                            </select>
                        </fieldset>
                        <fieldset>
                            <label>Email id:</label>
                            <label><input class=type="text" placeholder="Id" required name="Name">
                            </label>
                        </fieldset>
                        <fieldset>
                            <label>Email Date:</label>
                            <input type='date' name='initial_date'>
                        </fieldset>
                        <fieldset>
                            <label>Status Send </label>
                            <select name='status'>
                                <option value=>...</option>
                                <option value='True'>Email</option>
                                <option value='False'>Web</option>
                            </select>
                        </fieldset>

                        <fieldset>
                            <label>Email Date </label>
                            <select name='status'>
                                <option value=>...</option>
                                <option value='True'>True</option>
                                <option value='False'>False</option>
                            </select>
                        </fieldset>
                        <fieldset>
                            <label for="id_file_name">File</label>
                            <input type="file" name="file_name" multiple required id="id_file_name">
                        </fieldset>
                        <button class="btn btn-primary" style="float: right">Send</button>

                    </form>
                </div>
            </div>
        </div>


        <!-- Filter -->


        <div id="Filter" class="w3-modal">
            <div class="w3-modal-content w3-animate-zoom">
                <div class="w3-container w3-black">
            <span onclick="document.getElementById('Filter').style.display='none'"
                  class="w3-button w3-display-topright w3-large">x</span>
                    <h1>Filter Info</h1>
                </div>
                <div class="container">
                    <form id="filter_form" method="post">
                        {% csrf_token %}
                        <fieldset>
                            <label>Customer</label>
                            <select name='customer'>
                                {% if customers %}
                                    {% for customer in customers %}
                                        <option value={{ customer.id }}>{{ customer.name }}</option>
                                    {% endfor %}
                                {% endif %}
                            </select>
                        </fieldset>
                        <fieldset>
                            <label>Filter by</label>
                            <select name='filter_by'>
                                <option value=>...</option>
                                <option value='email'>Email</option>
                                <option value='date'>Date</option>
                            </select>
                        </fieldset>
                        <fieldset>
                            <label>Date Initial </label>
                            <input type='date' name='initial_date'>
                            <label>Finishied Date </label>
                            <input type='date' name='final_date'>
                        </fieldset>

                        <fieldset>
                            <label>Status Send </label>
                            <select name='status'>
                                <option value=>...</option>
                                <option value='True'>True</option>
                                <option value='False'>False</option>
                            </select>
                            <label>Send</label>
                            <button class="btn btn-primary" style="float: right">Send</button>
                        </fieldset>

                    </form>
                </div>
            </div>
        </div>
    </form>
</div>
<script>
    var filter = document.getElementById('filter_form')
    





</script>

</body>
</html>